In [2]:
import pandas as pd
import numpy as np

In [5]:
# the data is taken from the WDI data base https://datacatalog.worldbank.org/dataset/world-development-indicators
# for the speed purposes the data fis already extracted for Russia for the period 1994-2017
df = pd.read_excel('RUS.xlsx')
df.head()

,Indicator Name,Indicator Code,1994,1995,1996,1997,1998,1999,2000,2001,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,"2005 PPP conversion factor, GDP (LCU per inter...",PA.NUS.PPP.05,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.00,-9999.00,...,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.0
1,"2005 PPP conversion factor, private consumptio...",PA.NUS.PRVT.PP.05,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.00,-9999.00,...,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.00,-9999.0
2,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,-9999.0,92.69,93.36,...,96.64,96.93,97.22,97.42,97.62,97.81,98.03,98.15,98.25,-9999.0
3,Access to electricity (% of population),EG.ELC.ACCS.ZS,100.0,100.0,100.0,100.0,100.0,100.0,100.00,100.00,...,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,-9999.0
4,"Access to electricity, rural (% of rural popul...",EG.ELC.ACCS.RU.ZS,100.0,100.0,100.0,100.0,100.0,100.0,100.00,100.00,...,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,-9999.0

In [6]:
# extract the necessary variables and transpose the dataframe
df = df[df['Indicator Code'].isin(['NY.GDP.MKTP.CN', 'NE.CON.PRVT.CN', 'NE.EXP.GNFS.CN', 'NE.IMP.GNFS.CN', 'NE.GDI.TOTL.CN', 'NE.CON.GOVT.CN', 'BN.CAB.XOKA.GD.ZS', 'NY.GDP.DEFL.ZS', 'SP.POP.TOTL'])] 
df = df.drop(['Indicator Code'], axis=1)
df = df.T 
df.columns = df.iloc[0]
df = df[df['Current account balance (% of GDP)'] != 'Current account balance (% of GDP)']
df = df.apply(pd.to_numeric)
df.head()

Indicator Name,Current account balance (% of GDP),Exports of goods and services (current LCU),GDP (current LCU),GDP deflator (base year varies by country),General government final consumption expenditure (current LCU),Gross capital formation (current LCU),Households and NPISHs Final consumption expenditure (current LCU),Imports of goods and services (current LCU),"Population, total"
1994,2.263327,1.695343e+11,6.107500e+11,1.280118,1.166500e+11,1.559700e+11,3.102612e+11,1.416655e+11,148336000.0
1995,1.880487,4.184000e+11,1.428500e+12,3.123528,2.725000e+11,3.634000e+11,7.441000e+11,3.699000e+11,148375726.0
1996,2.579016,5.235000e+11,2.007800e+12,4.554163,3.914000e+11,4.752000e+11,1.044500e+12,4.387000e+11,148160042.0
1997,-0.206270,5.793000e+11,2.342500e+12,5.239982,4.935000e+11,5.148000e+11,1.282600e+12,5.277000e+11,147915307.0
1998,0.026226,8.210000e+11,2.629600e+12,6.211406,4.926000e+11,3.935000e+11,1.511200e+12,6.456000e+11,147670692.0

In [7]:
# save the data
df.to_excel("data.xlsx")